import config as c

error = "Ошибка"
info = "Инфо"
confirmation = "Подтвердите действие"
settings = "Настройки"
export_settings = "Экспортировать настройки"
clear = "Очистить"
last = "Отменить изменение"
change_color = "Сменить цвет"
rect = "Квадрат"
oval = "Овал"
line = "Линия"
dot = "Точка"
signature = "Подпись"
dash = "Пунктир"
curve = "Кривая"
brush = "Кисть"
eraser = "Ластик"
filling = "Заливка"
enter = "Ввод"
palette = "Выбрать цвет"
theme = "Темы"
welcome = "Добро пожаловать в Апофема2D"
settings_lang = "Язык приложения"
settings_lang_descr = "Язык приложения изменится после перезапуска"
settings_rutext = "Русский"
settings_entext = "Английский"
lang_alert = "Язык сменится после перезапуска программы"
settings_work_color = "Стиль"
settings_work_color_descr = "Измените стили при рисовании"
work_color = "Авто-цвет"
alert_auto_color1 = "Автоматическая смена цветов включена"
alert_auto_color2 = "Автоматическая смена цветов выключена"
user_color_alert = "Автоматическая смена цветов заменена на ваш цвет"
user_color_alert1 = "Некорретный HEX-код"
user_color_alert2 = "Цвет возвращён по умолчанию"
settings_scale = "Масштаб поля"
settings_scale_descr = "Измените размер клеток на поле"
settings_scale_alert = "Изменение масштаба полностью очистит поле. Продолжить?"
export_objects = "Экспортировать поле"
design = "Проектирование"
design_start = "Режим проектирования"
design_descr = '''
Нарисуйте фигуру на поле. Используйте
для этого инструмент "Кривая".
'''
design_descr_error = '''
Не удалось распознать фигуру
на поле =(
Попробуйте ещё раз или убедитесь,
что всё сделали верно
'''
design_start_btn = "Анализ"
design_delf_btn = "Обозначать вершины"
dm_figure = "Не опознано"
triangle = "Треугольник"
angle = "Угол"
rectangle = "Четырёхугольник"
square = "Квадрат" 
parallelogram = "Параллелограмм"
isoscelesT = "Равнобедренный треугольник"
equilateralT = "Равносторонний треугольник"
theme_mode = "Темы приложения"
standart_theme = "Стандарт"
HNY_theme = "Новогодняя"
dark_theme = "Тёмная"
light_theme = "Светлая"
cream_theme = "Крем"
restart = "Для применения изменений необходимо перезапустить программу. Перезапустить?"
file_error = "Неккоректное имя или тип файла"

# Английская версия
error2 = "Error"
info2 = "Info"
confirmation2 = "Confirm the action"
settings2 = "Settings"
export_settings2 = "Export settings"
clear2 = "Clear all"
last2 = "Undo change"
change_color2 = "Сhange color"
rect2 = "Rectangle"
oval2 = "Oval"
line2 = "Line"
dot2 = "Point"
signature2 = "Signature"
dash2 = "Dash"
curve2 = "Curve"
brush2 = "Brush"
eraser2 = "Eraser"
filling2 = "Filling"
enter2 = "Enter"
palette2 = "Choose color"
theme2 = "Themes"
welcome2 = "Welcome to Apothema2D"
settings_lang2 = "Programm language"
settings_lang_descr2 = "The language of the application will change after restarting"
settings_rutext2 = "Russian"
settings_entext2 = "English"
lang_alert2 = "The language of the application will change after restarting"
settings_work_color2 = "Style"
settings_work_color_descr2 = "Change the styles of the drawing"
work_color2 = "Auto-color"
alert_auto_color12 = "Auto-color is on"
alert_auto_color22 = "Auto-color is off"
user_color_alert2 = "Auto-color has been replaced with your color"
user_color_alert12 = "Invalid HEX-code"
user_color_alert22 = "The default color is returned"
settings_scale2 = "Field scale"
settings_scale_descr2 = "Change the scale of the cells on the field"
settings_scale_alert2 = "Changing the scale will completely clear the field. Continue?"
export_objects2 = "Export field"
design2 = "Design mode"
design_start2 = "Design mode"
design_descr2 = '''
Draw a shape. Use instrument "Curve" 
for it.
'''
design_descr_error2 = '''
Couldn't find a piece on the field. =(
Try again or make sure you
did everything right'''
design_start_btn2 = "Analyze"
design_delf_btn2 = "Mark vertexes"
dm_figure2 = "Figure not found"
triangle2 = "Triangle"
angle2 = "Angle"
rectangle2 = "Rectangle"
square2 = "Square" 
parallelogram2 = "Parallelogram"
isoscelesT2 = "isosceles triangle"
equilateralT2 = "equilateral triangle"
theme_mode2 = "Themes of app"
standart_theme2 = "Standart"
HNY_theme2 = "Christmas"
dark_theme2 = "Dark"
light_theme2 = "Light"
cream_theme2 = "Cream"
restart2 = "To apply changes, you need to restart programm. Restart?"
file_error2 = "Uncorrect name or type of file"
